 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/belts", type: :request do
  
  # Belt. As you add validations to Belt, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Belt.create! valid_attributes
      get belts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      belt = Belt.create! valid_attributes
      get belt_url(belt)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_belt_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      belt = Belt.create! valid_attributes
      get edit_belt_url(belt)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Belt" do
        expect {
          post belts_url, params: { belt: valid_attributes }
        }.to change(Belt, :count).by(1)
      end

      it "redirects to the created belt" do
        post belts_url, params: { belt: valid_attributes }
        expect(response).to redirect_to(belt_url(Belt.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Belt" do
        expect {
          post belts_url, params: { belt: invalid_attributes }
        }.to change(Belt, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post belts_url, params: { belt: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested belt" do
        belt = Belt.create! valid_attributes
        patch belt_url(belt), params: { belt: new_attributes }
        belt.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the belt" do
        belt = Belt.create! valid_attributes
        patch belt_url(belt), params: { belt: new_attributes }
        belt.reload
        expect(response).to redirect_to(belt_url(belt))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        belt = Belt.create! valid_attributes
        patch belt_url(belt), params: { belt: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested belt" do
      belt = Belt.create! valid_attributes
      expect {
        delete belt_url(belt)
      }.to change(Belt, :count).by(-1)
    end

    it "redirects to the belts list" do
      belt = Belt.create! valid_attributes
      delete belt_url(belt)
      expect(response).to redirect_to(belts_url)
    end
  end
end
