 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/class_instructors", type: :request do
  
  # ClassInstructor. As you add validations to ClassInstructor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ClassInstructor.create! valid_attributes
      get class_instructors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      class_instructor = ClassInstructor.create! valid_attributes
      get class_instructor_url(class_instructor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_class_instructor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      class_instructor = ClassInstructor.create! valid_attributes
      get edit_class_instructor_url(class_instructor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ClassInstructor" do
        expect {
          post class_instructors_url, params: { class_instructor: valid_attributes }
        }.to change(ClassInstructor, :count).by(1)
      end

      it "redirects to the created class_instructor" do
        post class_instructors_url, params: { class_instructor: valid_attributes }
        expect(response).to redirect_to(class_instructor_url(ClassInstructor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ClassInstructor" do
        expect {
          post class_instructors_url, params: { class_instructor: invalid_attributes }
        }.to change(ClassInstructor, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post class_instructors_url, params: { class_instructor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested class_instructor" do
        class_instructor = ClassInstructor.create! valid_attributes
        patch class_instructor_url(class_instructor), params: { class_instructor: new_attributes }
        class_instructor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the class_instructor" do
        class_instructor = ClassInstructor.create! valid_attributes
        patch class_instructor_url(class_instructor), params: { class_instructor: new_attributes }
        class_instructor.reload
        expect(response).to redirect_to(class_instructor_url(class_instructor))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        class_instructor = ClassInstructor.create! valid_attributes
        patch class_instructor_url(class_instructor), params: { class_instructor: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested class_instructor" do
      class_instructor = ClassInstructor.create! valid_attributes
      expect {
        delete class_instructor_url(class_instructor)
      }.to change(ClassInstructor, :count).by(-1)
    end

    it "redirects to the class_instructors list" do
      class_instructor = ClassInstructor.create! valid_attributes
      delete class_instructor_url(class_instructor)
      expect(response).to redirect_to(class_instructors_url)
    end
  end
end
