 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/pakua_classes", type: :request do
  
  # PakuaClass. As you add validations to PakuaClass, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PakuaClass.create! valid_attributes
      get pakua_classes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      pakua_class = PakuaClass.create! valid_attributes
      get pakua_class_url(pakua_class)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_pakua_class_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      pakua_class = PakuaClass.create! valid_attributes
      get edit_pakua_class_url(pakua_class)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PakuaClass" do
        expect {
          post pakua_classes_url, params: { pakua_class: valid_attributes }
        }.to change(PakuaClass, :count).by(1)
      end

      it "redirects to the created pakua_class" do
        post pakua_classes_url, params: { pakua_class: valid_attributes }
        expect(response).to redirect_to(pakua_class_url(PakuaClass.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PakuaClass" do
        expect {
          post pakua_classes_url, params: { pakua_class: invalid_attributes }
        }.to change(PakuaClass, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post pakua_classes_url, params: { pakua_class: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested pakua_class" do
        pakua_class = PakuaClass.create! valid_attributes
        patch pakua_class_url(pakua_class), params: { pakua_class: new_attributes }
        pakua_class.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the pakua_class" do
        pakua_class = PakuaClass.create! valid_attributes
        patch pakua_class_url(pakua_class), params: { pakua_class: new_attributes }
        pakua_class.reload
        expect(response).to redirect_to(pakua_class_url(pakua_class))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        pakua_class = PakuaClass.create! valid_attributes
        patch pakua_class_url(pakua_class), params: { pakua_class: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested pakua_class" do
      pakua_class = PakuaClass.create! valid_attributes
      expect {
        delete pakua_class_url(pakua_class)
      }.to change(PakuaClass, :count).by(-1)
    end

    it "redirects to the pakua_classes list" do
      pakua_class = PakuaClass.create! valid_attributes
      delete pakua_class_url(pakua_class)
      expect(response).to redirect_to(pakua_classes_url)
    end
  end
end
