 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/student_plans", type: :request do
  
  # StudentPlan. As you add validations to StudentPlan, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      StudentPlan.create! valid_attributes
      get student_plans_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      student_plan = StudentPlan.create! valid_attributes
      get student_plan_url(student_plan)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_student_plan_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      student_plan = StudentPlan.create! valid_attributes
      get edit_student_plan_url(student_plan)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new StudentPlan" do
        expect {
          post student_plans_url, params: { student_plan: valid_attributes }
        }.to change(StudentPlan, :count).by(1)
      end

      it "redirects to the created student_plan" do
        post student_plans_url, params: { student_plan: valid_attributes }
        expect(response).to redirect_to(student_plan_url(StudentPlan.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new StudentPlan" do
        expect {
          post student_plans_url, params: { student_plan: invalid_attributes }
        }.to change(StudentPlan, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post student_plans_url, params: { student_plan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested student_plan" do
        student_plan = StudentPlan.create! valid_attributes
        patch student_plan_url(student_plan), params: { student_plan: new_attributes }
        student_plan.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the student_plan" do
        student_plan = StudentPlan.create! valid_attributes
        patch student_plan_url(student_plan), params: { student_plan: new_attributes }
        student_plan.reload
        expect(response).to redirect_to(student_plan_url(student_plan))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        student_plan = StudentPlan.create! valid_attributes
        patch student_plan_url(student_plan), params: { student_plan: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested student_plan" do
      student_plan = StudentPlan.create! valid_attributes
      expect {
        delete student_plan_url(student_plan)
      }.to change(StudentPlan, :count).by(-1)
    end

    it "redirects to the student_plans list" do
      student_plan = StudentPlan.create! valid_attributes
      delete student_plan_url(student_plan)
      expect(response).to redirect_to(student_plans_url)
    end
  end
end
