 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tuition_fees", type: :request do
  
  # TuitionFee. As you add validations to TuitionFee, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TuitionFee.create! valid_attributes
      get tuition_fees_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tuition_fee = TuitionFee.create! valid_attributes
      get tuition_fee_url(tuition_fee)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tuition_fee_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      tuition_fee = TuitionFee.create! valid_attributes
      get edit_tuition_fee_url(tuition_fee)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TuitionFee" do
        expect {
          post tuition_fees_url, params: { tuition_fee: valid_attributes }
        }.to change(TuitionFee, :count).by(1)
      end

      it "redirects to the created tuition_fee" do
        post tuition_fees_url, params: { tuition_fee: valid_attributes }
        expect(response).to redirect_to(tuition_fee_url(TuitionFee.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TuitionFee" do
        expect {
          post tuition_fees_url, params: { tuition_fee: invalid_attributes }
        }.to change(TuitionFee, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post tuition_fees_url, params: { tuition_fee: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tuition_fee" do
        tuition_fee = TuitionFee.create! valid_attributes
        patch tuition_fee_url(tuition_fee), params: { tuition_fee: new_attributes }
        tuition_fee.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tuition_fee" do
        tuition_fee = TuitionFee.create! valid_attributes
        patch tuition_fee_url(tuition_fee), params: { tuition_fee: new_attributes }
        tuition_fee.reload
        expect(response).to redirect_to(tuition_fee_url(tuition_fee))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        tuition_fee = TuitionFee.create! valid_attributes
        patch tuition_fee_url(tuition_fee), params: { tuition_fee: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tuition_fee" do
      tuition_fee = TuitionFee.create! valid_attributes
      expect {
        delete tuition_fee_url(tuition_fee)
      }.to change(TuitionFee, :count).by(-1)
    end

    it "redirects to the tuition_fees list" do
      tuition_fee = TuitionFee.create! valid_attributes
      delete tuition_fee_url(tuition_fee)
      expect(response).to redirect_to(tuition_fees_url)
    end
  end
end
